export const refs = {
  btn: {
    btn_en: document.querySelector(".en"),
    btn_ua: document.querySelector(".ua"),
    btn_fr: document.querySelector(".fr"),
  },
  elements: {
    banner_info: document.querySelector(".banner_info"),
    button_info_1: document.querySelector(".button_info_1"),
    button_info_2: document.querySelector(".button_info_2"),
    best_food_text: document.querySelector(".best_food_text"),
    best_food_descr_text: document.querySelector(".best_food_descr_text"),
    best_food_discover: document.querySelector(".best_food_discover p"),
    bites: document.querySelector(".bites"),
    years: document.querySelector(".years"),
    cheese: document.querySelector(".cheese"),
    fries: document.querySelector(".fries"),
    noodles: document.querySelector(".noodles"),
    prawns: document.querySelector(".prawns"),
    rides: document.querySelector(".rides"),
    list_rest: document.querySelector(".list_rest"),
    list_city: document.querySelector(".list_city"),
    list_brand: document.querySelector(".list_brand"),
    list_more: document.querySelector(".list_more"),
    menu_list_1: document.querySelector(".menu_list_1"),
    menu_list_2: document.querySelector(".menu_list_2"),
    menu_list_3: document.querySelector(".menu_list_3"),
  },
};
